language: python

services:
  - docker

before_install:
 - docker swarm init
 - docker stack deploy -c ai-message_scrubber/docker-compose.yml message-scrubber

script:
 - cd ai-message_scrubber
 - bash ai-message_scrubber/ms-travis.sh