--- 
before_install: 
  - "wget -qO- https://toolbelt.heroku.com/install.sh | sh"
  - "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin"
  - "echo \"$HEROKU_PASSWORD\" | docker login -u \"$HEROKU_USERNAME\" --password-stdin registry.heroku.com"
  - "docker pull alabamaliquidservices/botic:latest-frontend"
  - "docker tag alabamaliquidservices/botic:latest-frontend registry.heroku.com/$HEROKU_APP_NAME/web"
branch: "\\#26_Deploying-Frontend"
deploy: 
  provider: script
language: bash
script: 
  - "docker push alabamaliquidservices/botic:latest-frontend"
  - "docker push registry.heroku.com/$HEROKU_APP_NAME/web"
  - "heroku container: web release --app $HEROKU_APP_NAME"
services: 
  - docker
sudo: required
true: ~
#used www.yamllint.com for linting