version: "0.1"
services:
  web:
    image: alabamaliquidservices/botic:latest-ms
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:5000"
    networks:
      - webnet
networks:
  webnet: